import { nanoid } from 'nanoid';
import * as Vue from 'vue';
import { markRaw, reactive } from 'vue';
import { enableVueBindings, syncedStore, getYjsValue } from '@syncedstore/core';
import { encodeStateAsUpdate } from 'yjs';

import { WebrtcProvider } from 'y-webrtc';
import { IndexeddbPersistence } from 'y-indexeddb';
import EventEmitter from '@/utils/event';
import LocalFilePersistence from './persist';

// import * as T from "./types"
// import { DocTypeDescription } from '@syncedstore/core/types/doc';

enableVueBindings(Vue);

export default class SyncedDocument extends EventEmitter {
    constructor(storeStructure) {
        super();
        this.syncInitialized = false;
        this.storeStructure = storeStructure;
        this.store = markRaw(syncedStore(storeStructure));
        this.localData = reactive({ ...storeStructure });
        this.users = reactive({});
        this.localUser = reactive({});
        this.remoteUpdated = false;
        this.awarenessHeartbeat = null;
        console.warn = () => null; // Supress the numerous warnings generated by SyncedStore.
    }

    materializeRootTypes() {
        const rootTypes = [];
        Object.keys(this.storeStructure).forEach((key) => {
            // SyncedStore creates root Yjs types lazily. Touch them before encoding.
            rootTypes.push(this.store[key]);
        });
        return rootTypes;
    }

    initSync(documentId) {
        console.log(`[Sync][initSync] Initializing sync with docID ${documentId}.`);
        Object.keys(this.users).forEach((userId) => delete this.users[userId]);
        this.store.metadata.id = documentId || nanoid();
        // this.store.metadata.id = this.store.metadata.id;
        this.materializeRootTypes();

        const doc = getYjsValue(this.store);
        try {
            encodeStateAsUpdate(doc);
        } catch (error) {
            console.error('[Sync][initSync] Cannot encode Yjs document before starting sync.', error);
            this.emit('sync-error', error);
            return;
        }

        this.syncProvider = new WebrtcProvider(this.store.metadata.id, doc, { signaling: ['wss://signal.shengchen.io'] });
        console.log('[Sync][initSync].');
        this.syncProvider.awareness.on('change', this.handleChanges.bind(this));

        // Generate a random user id, then update the awareness.
        this.userId = nanoid();
        this.syncProvider.awareness.setLocalStateField('id', this.userId);
        this.syncProvider.awareness.setLocalStateField('lastSeen', Date.now());
        // if (!this.store.metadata.name) this.store.metadata.name = 'Untitled';

        Object.assign(this.localUser, { id: this.userId });

        this.syncInitialized = true;
        this.awarenessHeartbeat = setInterval(() => {
            this.updateAwareness('lastSeen', Date.now());
        }, 2500);
    }

    initPersistence(filePath, overwrite) {
        const doc = getYjsValue(this.store);
        const electron = Boolean(window.intrigue?.isElectron);

        if (!electron && filePath && !this.store.metadata.id) {
            this.store.metadata.id = filePath;
        }

        this.saveProvider = electron
            ? new LocalFilePersistence(filePath, doc, overwrite)
            : new IndexeddbPersistence(filePath || this.store.metadata.id, doc);

        this.saveProvider.on('synced', () => {
            console.log('[Sync][saveProvider@synced] Save provider synced.', this.store.metadata.id);
            const migrated = typeof this.migrateLoadedDocument === 'function'
                ? this.migrateLoadedDocument()
                : false;
            const documentId = this.store.metadata.id || (!electron ? filePath : undefined);
            if (!this.syncInitialized) this.initSync(documentId);
            if (migrated) this.emit('migrated');
            this.emit('synced');
        });

        this.saveProvider.on('save', () => {
            console.log('[Sync][saveProvider@synced] Saving to disk...');
            this.emit('save');
        });

        this.saveProvider.on('saved', () => {
            console.log('[Sync][saveProvider@synced] Save provider saved.');
            this.emit('saved');
        });

        this.saveProvider.on('save-error', (error) => {
            console.error('[Sync][saveProvider@save-error] Failed to save.', error);
            this.emit('save-error', error);
        });
    }

    close() {
        if (this.awarenessHeartbeat) {
            clearInterval(this.awarenessHeartbeat);
            this.awarenessHeartbeat = null;
        }
        if (this.syncProvider) {
            this.syncProvider.awareness.setLocalState(null);
            this.syncProvider.destroy();
        }
    }

    // eslint-disable-next-line
    updateAwareness(key, value) {
        if (!this.syncInitialized) return;
        this.syncProvider.awareness.setLocalStateField(key, value);
    }

    registerAwarenessCallback(key, callback) {
        this.syncProvider.awareness.on(key, callback);
    }

    handleChanges() {
        const awarenessInfo = [...this.syncProvider.awareness.getStates().values()];
        const onlineUsers = new Set();
        const offlineUsers = new Set(Object.keys(this.users));

        awarenessInfo.forEach((user) => {
            if (!user?.id) return;
            onlineUsers.add(user.id);
            offlineUsers.delete(user.id);

            if (!this.users[user.id]) this.users[user.id] = {};
            Object.entries(user).forEach(([key, value]) => {
                this.users[user.id][key] = value;
            });
        });

        offlineUsers.forEach((userId) => delete this.users[userId]);
    }

    stringify() {
        return JSON.stringify(this.store);
    }
}
