const tutorialData = {
    metadata: { version: '1.4.0', id: 'DUyn-oWkhA3ioJ41PHTPy' },
    nodes: {
        '_3bC_kUXPQ7dNF-dsrpCi': {
            id: '_3bC_kUXPQ7dNF-dsrpCi',
            type: 'note',
            content:
                '<h1>Hello! Welcome to Intrigue 👋</h1><p></p><p>Using this app, you can quickly write down your ideas and corresponding references, and make your academic writing faster.</p>',
            links: ['R0KxFeS_32b7A5x4_DEhZ', '-kO-82EifQz8eOs_LUqRQ', 'mJdSCPh6ASGxVOTMLcu2h'],
            parent: null,
            children: [],
            identifier: null,
            literature: null,
            x: 177.44285824718247,
            y: 172.15194775076841,
            w: 416,
            h: 104,
        },
        'lMQ0-FsEiJ-xrSMRYbroB': {
            id: 'lMQ0-FsEiJ-xrSMRYbroB',
            type: 'note',
            content:
                '<h2>Inspiration</h2><p></p><p>Intrigue is heavily inspired by&nbsp;<strong>Victor Margolin</strong>’s method of organizing research literature and writing, which makes use of note cards and literature canvases.</p>',
            links: ['-kO-82EifQz8eOs_LUqRQ'],
            parent: null,
            children: ['vIwjMVNGYkH27xW7ohqF8'],
            identifier: null,
            literature: null,
            x: 177.44285824718247,
            y: 353.45584325230527,
            w: 416,
            h: 114,
        },
        vIwjMVNGYkH27xW7ohqF8: {
            id: 'vIwjMVNGYkH27xW7ohqF8',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://www.youtube.com/watch?v=Kxyy0THLfuI">https://www.youtube.com/watch?v=Kxyy0THLfuI</a></p>',
            links: ['pterRXoPSKzgCDaNsC83x', 'BhptsYJKozbH78UDCnPqO'],
            parent: 'lMQ0-FsEiJ-xrSMRYbroB',
            children: [],
            identifier: 'https://www.youtube.com/watch?v=Kxyy0THLfuI',
            literature: null,
            x: 305.00168959672135,
            y: 510.0043472711194,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'The process of writing World History of Design',
            author: [{ family: 'Web link' }],
            record: {
                title: 'The process of writing World History of Design',
                author: [{ family: 'Web link' }],
                identifier: 'https://www.youtube.com/watch?v=Kxyy0THLfuI',
            },
        },
        SkEDT5rpM2mHNdBPbrDZ6: {
            id: 'SkEDT5rpM2mHNdBPbrDZ6',
            type: 'note',
            content: '<p>This is a <strong>reference</strong>. Try double-clicking it!</p>',
            links: ['pterRXoPSKzgCDaNsC83x'],
            parent: null,
            children: [],
            identifier: null,
            literature: null,
            x: 285.7206507963114,
            y: 587.1285024727587,
            w: 200,
            h: 15,
        },
        Jx2OSjcSFnoAbVCuqmLad: {
            id: 'Jx2OSjcSFnoAbVCuqmLad',
            type: 'note',
            content:
                '<h2>This is a <strong>note</strong>.</h2><p></p><p>Notes comes with&nbsp;<strong>WYSIWYG markdown</strong>&nbsp;support.</p>',
            links: ['C8tZCru6N8C39KvQx3MYG', 'R0KxFeS_32b7A5x4_DEhZ'],
            parent: null,
            children: ['VWozU9koXfzY_FuNn3Toa'],
            identifier: null,
            literature: null,
            x: -266.1990848654199,
            y: 353.3459070177895,
            w: 330,
            h: 76,
        },
        VWozU9koXfzY_FuNn3Toa: {
            id: 'VWozU9koXfzY_FuNn3Toa',
            type: 'note',
            content:
                '<p>Notes can be&nbsp;<strong>snapped</strong>&nbsp;together, by dragging one onto another.</p>',
            links: [],
            parent: 'Jx2OSjcSFnoAbVCuqmLad',
            children: [],
            identifier: null,
            literature: null,
            x: -157.7432416131146,
            y: 526.875256221478,
            w: 200,
            h: 15,
        },
        FpYfMmGwXc6d9C5_oUvMX: {
            id: 'FpYfMmGwXc6d9C5_oUvMX',
            type: 'note',
            content: '<p>Snap me to the note above!</p>',
            links: [],
            parent: null,
            children: [],
            identifier: null,
            literature: null,
            x: -202.33064383906233,
            y: 496.74863309583753,
            w: 200,
            h: 15,
        },
        'vCDV3Nui8VXRY-lcW-lPr': {
            id: 'vCDV3Nui8VXRY-lcW-lPr',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax">https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax</a></p>',
            links: ['C8tZCru6N8C39KvQx3MYG'],
            parent: null,
            children: [],
            identifier:
                'https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax',
            literature: null,
            x: -587.951419847259,
            y: 443.12324393219785,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'Basic writing and formatting syntax - GitHub Docs',
            author: [{ family: 'Web link' }],
            record: {
                title: 'Basic writing and formatting syntax - GitHub Docs',
                author: [{ family: 'Web link' }],
                identifier:
                    'https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax',
            },
        },
        'hWTpXY-uSv2j8jG6d-77S': {
            id: 'hWTpXY-uSv2j8jG6d-77S',
            type: 'note',
            content:
                "<h2>References</h2><p></p><p>Many things can be&nbsp;<strong>automatically</strong>&nbsp;turned into reference notes, just by&nbsp;<strong>pasting in the identifiers</strong>:</p><p></p><ul><li><p>ISBN</p></li><li><p>DOI</p></li><li><p>Web Link</p></li><li><p>JSON from Intrigue's Zotero exporter</p></li></ul>",
            links: ['BhptsYJKozbH78UDCnPqO', 'idg-ugZrOU9uQs_ZIE-TA'],
            parent: null,
            children: [],
            identifier: null,
            literature: null,
            x: -179.59221908495297,
            y: 640.1423940523325,
            w: 264,
            h: 214,
        },
        'vL4AHtMN_Hk02dELc-0Yy': {
            id: 'vL4AHtMN_Hk02dELc-0Yy',
            type: 'note',
            content:
                '<h2>↗️ See the button(s) in the upper-right corner?</h2><p></p><p>You can click <strong>"Share"</strong> to get a web link, which you can share with others to collaborate. </p>',
            links: ['mJdSCPh6ASGxVOTMLcu2h'],
            parent: null,
            children: ['yGO0qi387djHjiJoBIZVm'],
            identifier: null,
            literature: null,
            x: 717.7364264179943,
            y: 354.5509719428151,
            w: 333,
            h: 123,
        },
        'CI-b7gYjpvc3uqqDmUKth': {
            id: 'CI-b7gYjpvc3uqqDmUKth',
            type: 'note',
            content:
                '<p>If you receive a link and have the <strong>desktop version</strong> of Intrigue, you can click also go to <strong>File &gt; Open URL...</strong> to open it there.</p>',
            links: [],
            parent: 'yGO0qi387djHjiJoBIZVm',
            children: [],
            identifier: null,
            literature: null,
            x: 723.7617510431223,
            y: 616.0500606733734,
            w: 322,
            h: 60,
        },
        yGO0qi387djHjiJoBIZVm: {
            id: 'yGO0qi387djHjiJoBIZVm',
            type: 'note',
            content:
                '<p>If you select a portion of this document, you can click the button to <strong>share that specific portion</strong> as well!</p>',
            links: [],
            parent: 'vL4AHtMN_Hk02dELc-0Yy',
            children: ['CI-b7gYjpvc3uqqDmUKth'],
            identifier: null,
            literature: null,
            x: 723.7617510431223,
            y: 528.0803211465036,
            w: 200,
            h: 15,
        },
        iu18D6S21cdyI3VZZHjL0: {
            id: 'iu18D6S21cdyI3VZZHjL0',
            type: 'note',
            content:
                "<h2>Intrigue uses offline-first distributed collaborative editing.</h2><p></p><p>What does it mean? Let's break it down.</p>",
            links: [],
            parent: null,
            children: ['qOALaeb_CJTSsQ3d5FRfr'],
            identifier: null,
            literature: null,
            x: 712.313634255379,
            y: 655.2146707367059,
            w: 344,
            h: 104,
        },
        qOALaeb_CJTSsQ3d5FRfr: {
            id: 'qOALaeb_CJTSsQ3d5FRfr',
            type: 'note',
            content:
                '<p><strong>Collaborative editing:&nbsp;</strong>You can edit this document together with other people over the internet.</p>',
            links: [],
            parent: 'iu18D6S21cdyI3VZZHjL0',
            children: ['i9401DLUIMK3gc5u1j-_e'],
            identifier: null,
            literature: null,
            x: 752.0807767812242,
            y: 805.8477863649077,
            w: 200,
            h: 15,
        },
        'i9401DLUIMK3gc5u1j-_e': {
            id: 'i9401DLUIMK3gc5u1j-_e',
            type: 'note',
            content:
                "<p><strong>Distributed:</strong>&nbsp;There's no central server that stores your data. Each collaborator holds their own copy, and they directly communicate with each other to keep in sync.</p>",
            links: ['ogoINFrk2c8WcJznsZSG9', '5PfHVPNp0JMYLAa-RIsAi'],
            parent: 'qOALaeb_CJTSsQ3d5FRfr',
            children: ['b5nMGJvjeLapv6nC2ZVaz'],
            identifier: null,
            literature: null,
            x: 724.3642835056352,
            y: 848.0250587408043,
            w: 200,
            h: 15,
        },
        b5nMGJvjeLapv6nC2ZVaz: {
            id: 'b5nMGJvjeLapv6nC2ZVaz',
            type: 'note',
            content:
                "<p><strong>Offline-first:</strong>&nbsp;Because each person has their own copy, you don't need to be online to edit this file. The updates you made will be sent to your collaborators the next time you are all online.</p>",
            links: ['H1nV67Y0PmldP37MS67VE'],
            parent: 'i9401DLUIMK3gc5u1j-_e',
            children: [],
            identifier: null,
            literature: null,
            x: 714.7237641054302,
            y: 907.0732400670594,
            w: 200,
            h: 15,
        },
        k1k87jvJiRS8lnXo11WsY: {
            id: 'k1k87jvJiRS8lnXo11WsY',
            type: 'note',
            content:
                '<p>This does mean that&nbsp;<strong>someone has to have the file open</strong>&nbsp;when a new person logs on, in order for the new person to get the file content.</p>',
            links: ['ogoINFrk2c8WcJznsZSG9'],
            parent: null,
            children: ['ruDrpYVn_1XnZqyCxKzmP'],
            identifier: null,
            literature: null,
            x: 405.6246108363602,
            y: 811.8731109900358,
            w: 207,
            h: 98,
        },
        ruDrpYVn_1XnZqyCxKzmP: {
            id: 'ruDrpYVn_1XnZqyCxKzmP',
            type: 'note',
            content:
                '<p>But if not, no worries. The person can still add to the document. The next time they and someone holding the older content are both online, they will get synced.</p>',
            links: [],
            parent: 'k1k87jvJiRS8lnXo11WsY',
            children: [],
            identifier: null,
            literature: null,
            x: 555.0526615395363,
            y: 996.2480445189548,
            w: 200,
            h: 15,
        },
        dawfps9Utt_AaW01pxEci: {
            id: 'dawfps9Utt_AaW01pxEci',
            type: 'note',
            content:
                "<p>If you monitor Intrigue's web traffic, you might notice requests going to https://signal.shengchen.io. That's the signaling server I'm hosting on my server.</p>",
            links: ['5PfHVPNp0JMYLAa-RIsAi'],
            parent: null,
            children: ['u9BCW5UFKcfu8TuCDiRQS'],
            identifier: null,
            literature: null,
            x: 1144.9319423395746,
            y: 811.8731109900358,
            w: 232,
            h: 98,
        },
        u9BCW5UFKcfu8TuCDiRQS: {
            id: 'u9BCW5UFKcfu8TuCDiRQS',
            type: 'note',
            content:
                "<p>This is to let people editing the document discover each other. No actual data of your document is ever kept there.<br><br><em>(I wouldn't be able to afford the storage fees, anyway!)</em></p>",
            links: [],
            parent: 'dawfps9Utt_AaW01pxEci',
            children: [],
            identifier: null,
            literature: null,
            x: 1207.5953184409066,
            y: 969.7366161683913,
            w: 200,
            h: 15,
        },
        'xdkb5Rbx7yvAzs-_VLt_t': {
            id: 'xdkb5Rbx7yvAzs-_VLt_t',
            type: 'note',
            content:
                '<h3>Intrigue uses SyncedStore and Yjs to keep you in sync.</h3><p></p><p>Under the hood, they use algorithms called CRDTs to ensure that all edits are merged correctly, even if made offline.</p>',
            links: ['H1nV67Y0PmldP37MS67VE'],
            parent: null,
            children: ['vDWXEaebV9nw7kH9JmLuz'],
            identifier: null,
            literature: null,
            x: 711.0305686488343,
            y: 1020.0391168216672,
            w: 346,
            h: 129,
        },
        vDWXEaebV9nw7kH9JmLuz: {
            id: 'vDWXEaebV9nw7kH9JmLuz',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://yjs.dev">https://yjs.dev</a></p>',
            links: [],
            parent: 'xdkb5Rbx7yvAzs-_VLt_t',
            children: ['ojZN101fMLl2-wRl71XbK'],
            identifier: 'https://yjs.dev',
            literature: null,
            x: 584.2270712220159,
            y: 1196.274486126737,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'Yjs | Homepage',
            author: [{ family: 'Web link' }],
            record: {
                title: 'Yjs | Homepage',
                author: [{ family: 'Web link' }],
                identifier: 'https://yjs.dev',
            },
        },
        'ojZN101fMLl2-wRl71XbK': {
            id: 'ojZN101fMLl2-wRl71XbK',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/yousefed/SyncedStore">https://github.com/yousefed/SyncedStore</a></p>',
            links: [],
            parent: 'vDWXEaebV9nw7kH9JmLuz',
            children: ['VQhir_1SHkY3ZqQ5mWuZQ'],
            identifier: 'https://github.com/yousefed/SyncedStore',
            literature: null,
            x: 774.7905193323759,
            y: 1295.1382298832395,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'GitHub - YousefED/SyncedStore: SyncedStore CRDT is an easy-to-use library for building live, collaborative applications that sync automatically.',
            author: [{ family: 'Web link' }],
            record: {
                title: 'GitHub - YousefED/SyncedStore: SyncedStore CRDT is an easy-to-use library for building live, collaborative applications that sync automatically.',
                author: [{ family: 'Web link' }],
                identifier: 'https://github.com/yousefed/SyncedStore',
            },
        },
        VQhir_1SHkY3ZqQ5mWuZQ: {
            id: 'VQhir_1SHkY3ZqQ5mWuZQ',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://crdt.tech">https://crdt.tech</a></p>',
            links: [],
            parent: 'ojZN101fMLl2-wRl71XbK',
            children: ['h33inDg2RtZd59Kjf9uvN'],
            identifier: 'https://crdt.tech',
            literature: null,
            x: 740.4031301996794,
            y: 1333.824042657523,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'About CRDTs • Conflict-free Replicated Data Types',
            author: [{ family: 'Web link' }],
            record: {
                title: 'About CRDTs • Conflict-free Replicated Data Types',
                author: [{ family: 'Web link' }],
                identifier: 'https://crdt.tech',
            },
        },
        h33inDg2RtZd59Kjf9uvN: {
            id: 'h33inDg2RtZd59Kjf9uvN',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://www.inkandswitch.com/essay/local-first/">https://www.inkandswitch.com/essay/local-first/</a></p>',
            links: [],
            parent: 'VQhir_1SHkY3ZqQ5mWuZQ',
            children: [],
            identifier: 'https://www.inkandswitch.com/essay/local-first/',
            literature: null,
            x: 405.12608615588795,
            y: 1071.4410995356457,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'Local-first software: You own your data, in spite of the cloud',
            author: [{ family: 'Web link' }],
            record: {
                title: 'Local-first software: You own your data, in spite of the cloud',
                author: [{ family: 'Web link' }],
                identifier: 'https://www.inkandswitch.com/essay/local-first/',
            },
        },
        'UbU5F3HGXwiLxkP79H-Bd': {
            id: 'UbU5F3HGXwiLxkP79H-Bd',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/shaunabanana/intrigue/blob/main/assets/Intrigue.js">https://github.com/shaunabanana/intrigue/blob/main/assets/Intrigue.js</a></p>',
            links: ['hElGKKmED13LyB34N6gKH'],
            parent: 'JIrbOTzq80YaOC_DZrklS',
            children: ['8qcsVdU6AQ4D2OOXlvPFe'],
            identifier: 'https://github.com/shaunabanana/intrigue/blob/main/assets/Intrigue.js',
            literature: null,
            x: -156.66729299648864,
            y: 1140.3462361891438,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'intrigue/assets/Intrigue.js at main · shaunabanana/intrigue',
            author: [{ family: 'Web link' }],
            record: {
                title: 'intrigue/assets/Intrigue.js at main · shaunabanana/intrigue',
                author: [{ family: 'Web link' }],
                identifier: 'https://github.com/shaunabanana/intrigue/blob/main/assets/Intrigue.js',
            },
        },
        JIrbOTzq80YaOC_DZrklS: {
            id: 'JIrbOTzq80YaOC_DZrklS',
            type: 'note',
            content:
                "<h3>How to use the Zotero exporter:</h3><ul><li><p>Place the exporter code in the translators folder of Zotero.</p></li><li><p>In Zotero export settings, set Quick Copy to Intrigue.</p></li><li><p>Select the record you'd like to export, then press the Quick Copy keyboard shortcut to copy it.</p></li><li><p>In Intrigue, double click to create a new note, then paste in the content.</p></li></ul>",
            links: ['idg-ugZrOU9uQs_ZIE-TA'],
            parent: null,
            children: ['UbU5F3HGXwiLxkP79H-Bd'],
            identifier: null,
            literature: null,
            x: -181.02502696548197,
            y: 901.0673201407969,
            w: 267,
            h: 73,
        },
        'rh57D6byyZb0DF-xqnVlF': {
            id: 'rh57D6byyZb0DF-xqnVlF',
            type: 'note',
            content: '<p>This is the exporter</p>',
            links: ['hElGKKmED13LyB34N6gKH'],
            parent: null,
            children: [],
            identifier: null,
            literature: null,
            x: -397.24632694036507,
            y: 1102.9628729072842,
            w: 126,
            h: 23,
        },
        A_5alVSvbk6MyfbgzuyZr: {
            id: 'A_5alVSvbk6MyfbgzuyZr',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://www.zotero.org/support/zotero_data#locating_your_zotero_data">https://www.zotero.org/support/zotero_data#locating_your_zotero_data</a></p>',
            links: [],
            parent: '8qcsVdU6AQ4D2OOXlvPFe',
            children: ['phkaFLz2r6SfX9SchgqL_'],
            identifier: 'https://www.zotero.org/support/zotero_data#locating_your_zotero_data',
            literature: null,
            x: -114.80299293891136,
            y: 1274.9468628018774,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'The Zotero Data Directory | Zotero Documentation',
            author: [{ family: 'Web link' }],
            record: {
                title: 'The Zotero Data Directory | Zotero Documentation',
                author: [{ family: 'Web link' }],
                identifier: 'https://www.zotero.org/support/zotero_data#locating_your_zotero_data',
            },
        },
        '8qcsVdU6AQ4D2OOXlvPFe': {
            id: '8qcsVdU6AQ4D2OOXlvPFe',
            type: 'note',
            content:
                '<p>Locate your Zotero library according to the guide below, then put the exporter into the <strong>"translators"</strong> folder.</p>',
            links: [],
            parent: 'UbU5F3HGXwiLxkP79H-Bd',
            children: ['A_5alVSvbk6MyfbgzuyZr'],
            identifier: null,
            literature: null,
            x: 152.66011887092833,
            y: 1251.096649009917,
            w: 200,
            h: 15,
        },
        phkaFLz2r6SfX9SchgqL_: {
            id: 'phkaFLz2r6SfX9SchgqL_',
            type: 'note',
            content: '<p>Finally, set up your Quick Copy:</p>',
            links: [],
            parent: 'A_5alVSvbk6MyfbgzuyZr',
            children: ['Gi0LE2qPvoPf979rbTSYe'],
            identifier: null,
            literature: null,
            x: -14.29137767279326,
            y: 1380.5692381662725,
            w: 200,
            h: 15,
        },
        Gi0LE2qPvoPf979rbTSYe: {
            id: 'Gi0LE2qPvoPf979rbTSYe',
            type: 'reference',
            content:
                '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://www.zotero.org/support/preferences/export#quick_copy">https://www.zotero.org/support/preferences/export#quick_copy</a></p>',
            links: [],
            parent: 'phkaFLz2r6SfX9SchgqL_',
            children: [],
            identifier: 'https://www.zotero.org/support/preferences/export#quick_copy',
            literature: null,
            x: -186.35363431479203,
            y: 1453.823466241579,
            w: 200,
            h: 15,
            referenceType: 'url',
            color: 'blue',
            title: 'Export | Zotero Documentation',
            author: [{ family: 'Web link' }],
            record: {
                title: 'Export | Zotero Documentation',
                author: [{ family: 'Web link' }],
                identifier: 'https://www.zotero.org/support/preferences/export#quick_copy',
            },
        },
    },
    links: {
        C8tZCru6N8C39KvQx3MYG: {
            id: 'C8tZCru6N8C39KvQx3MYG',
            source: 'Jx2OSjcSFnoAbVCuqmLad',
            target: 'vCDV3Nui8VXRY-lcW-lPr',
            sourceHandle: 'left',
            targetHandle: 'right',
        },
        R0KxFeS_32b7A5x4_DEhZ: {
            id: 'R0KxFeS_32b7A5x4_DEhZ',
            source: '_3bC_kUXPQ7dNF-dsrpCi',
            target: 'Jx2OSjcSFnoAbVCuqmLad',
            sourceHandle: 'bottom',
            targetHandle: 'top',
        },
        '-kO-82EifQz8eOs_LUqRQ': {
            id: '-kO-82EifQz8eOs_LUqRQ',
            source: '_3bC_kUXPQ7dNF-dsrpCi',
            target: 'lMQ0-FsEiJ-xrSMRYbroB',
            sourceHandle: 'bottom',
            targetHandle: 'top',
        },
        pterRXoPSKzgCDaNsC83x: {
            id: 'pterRXoPSKzgCDaNsC83x',
            source: 'SkEDT5rpM2mHNdBPbrDZ6',
            target: 'vIwjMVNGYkH27xW7ohqF8',
            sourceHandle: 'top',
            targetHandle: 'bottom',
        },
        BhptsYJKozbH78UDCnPqO: {
            id: 'BhptsYJKozbH78UDCnPqO',
            source: 'vIwjMVNGYkH27xW7ohqF8',
            target: 'hWTpXY-uSv2j8jG6d-77S',
            sourceHandle: 'left',
            targetHandle: 'top',
        },
        mJdSCPh6ASGxVOTMLcu2h: {
            id: 'mJdSCPh6ASGxVOTMLcu2h',
            source: '_3bC_kUXPQ7dNF-dsrpCi',
            target: 'vL4AHtMN_Hk02dELc-0Yy',
            sourceHandle: 'bottom',
            targetHandle: 'top',
        },
        ogoINFrk2c8WcJznsZSG9: {
            id: 'ogoINFrk2c8WcJznsZSG9',
            source: 'i9401DLUIMK3gc5u1j-_e',
            target: 'k1k87jvJiRS8lnXo11WsY',
            sourceHandle: 'left',
            targetHandle: 'right',
        },
        '5PfHVPNp0JMYLAa-RIsAi': {
            id: '5PfHVPNp0JMYLAa-RIsAi',
            source: 'i9401DLUIMK3gc5u1j-_e',
            target: 'dawfps9Utt_AaW01pxEci',
            sourceHandle: 'right',
            targetHandle: 'left',
        },
        H1nV67Y0PmldP37MS67VE: {
            id: 'H1nV67Y0PmldP37MS67VE',
            source: 'b5nMGJvjeLapv6nC2ZVaz',
            target: 'xdkb5Rbx7yvAzs-_VLt_t',
            sourceHandle: 'bottom',
            targetHandle: 'top',
        },
        hElGKKmED13LyB34N6gKH: {
            id: 'hElGKKmED13LyB34N6gKH',
            source: 'rh57D6byyZb0DF-xqnVlF',
            target: 'UbU5F3HGXwiLxkP79H-Bd',
            sourceHandle: 'right',
            targetHandle: 'left',
        },
        'idg-ugZrOU9uQs_ZIE-TA': {
            id: 'idg-ugZrOU9uQs_ZIE-TA',
            source: 'hWTpXY-uSv2j8jG6d-77S',
            target: 'JIrbOTzq80YaOC_DZrklS',
            sourceHandle: 'bottom',
            targetHandle: 'top',
        },
    },
    fragment: '',
};

export default tutorialData;
